CREATE DATABASE PGDB
USE PGDB;

CREATE TABLE [UploadFilesDB]
(
[ID] INT NOT NULL IDENTITY,
[FileName] VARCHAR(500),
CONSTRAINT PK_Primarykey PRIMARY KEY ([ID])
)

INSERT INTO [UploadFilesDB] VALUES ('File1.pdf');
SELECT * FROM [UploadFilesDB]

